name: Generate WebP Photos List

on:
  schedule:
    - cron: '0 0 * * 1'  # 每周一UTC 0点执行
  push:
    paths:
      - 'img/**'

jobs:
  generate-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Grant write permissions  
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Generate jsDelivr links for WebP
        run: |
          mkdir -p tmp
          find img/ -type f -iname "*.webp" > tmp/all_webp.txt
          cat tmp/all_webp.txt | while read -r file; do
            relative_path="${file#img/}"
            echo "https://cdn.jsdelivr.net/gh/${{ github.repository }}/${{ github.sha }}/img/$relative_path"
          done > photos.txt
          count=$(wc -l < photos.txt)
          echo "Generated $count WebP image links"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto: Update photos.txt with $count WebP links"
          file_pattern: photos.txt
