# .github/workflows/generate_photos_txt.yml
name: Generate WebP Photos List

on:
  schedule:
    - cron: '0 0 * * 1'  # 每天 UTC 0 点执行
  push:
    paths:
      - 'img/**'        # 当 img 目录有变更时触发

jobs:
  generate-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史记录

      - name: Generate jsDelivr links for WebP
        run: |
          mkdir -p tmp
          find img/ -type f -iname "*.webp" > tmp/all_webp.txt
          cat tmp/all_webp.txt | while read -r file; do
            relative_path="${file#img/}"
            echo "https://cdn.jsdelivr.net/gh/${{ github.repository }}/${{ github.sha }}/img/$relative_path"
          done > photos.txt
          count=$(wc -l < photos.txt)
          echo "Generated $count WebP image links"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto: Update photos.txt with $count WebP links"
          file_pattern: photos.txt
          fail_on_empty_changes: false
